
   export const  GET_PRODUCTS="GET_PRODUCTS";
   export const  SELECTED_PRODUCT="SELECTED_PRODUCT";
    export const DELETE_SELECTED_PRODUCT=" DELETE_SELECTED_PRODUCT";
    export const  ADD_PRODUCT="ADD_PRODUCT";
    export const  UPDATE_PRODUCT="UPDATE_PRODUCT";
    export const GET_SINGLE_PRODUCT="GET_SINGLE_PRODUCT";

    
